name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: kivy/buildozer:latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with Buildozer
        run: |
          # On utilise 'yes' pour répondre automatiquement 'y' à toutes les questions de Buildozer
          yes | buildozer android debug
          
